// <auto-generated />
using System;
using CleanArchitecture.PracticalTest.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchitecture.PracticalTest.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20260304165230_UpdateIdsDuplicated")]
    partial class UpdateIdsDuplicated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Common.PaqueteHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("FechaHoraCambio")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_hora_cambio");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paquete_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_paquete_historial");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_paquete_historial_estado_id");

                    b.HasIndex("PaqueteId")
                        .HasDatabaseName("ix_paquete_historial_paquete_id");

                    b.ToTable("paquete_historial", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EstadoDescripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado_descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.ToTable("estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d12a3456-7890-abcd-ef01-234567890abc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EstadoDescripcion = "Registrado",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e23b4567-8901-bcde-f012-345678901bcd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EstadoDescripcion = "En Bodega",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f34c5678-9012-cdef-0123-456789012cde"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EstadoDescripcion = "En Transito",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d12a3456-7890-abcd-ef01-234567890abe"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EstadoDescripcion = "En Reparto",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e23b4567-8901-bcde-f012-345678901bce"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EstadoDescripcion = "Entregado",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f34c5678-9012-cdef-0123-456789012cdc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            EstadoDescripcion = "Devuelto",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entities.Paquete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Alto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("alto");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ancho");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Distancia")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Largo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("largo");

                    b.Property<string>("NumeroRastreo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_rastreo");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.Property<Guid?>("RutaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruta_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("Volumen")
                        .HasColumnType("numeric")
                        .HasColumnName("volumen");

                    b.HasKey("Id")
                        .HasName("pk_paquetes");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_paquetes_estado_id");

                    b.HasIndex("RutaId")
                        .HasDatabaseName("ix_paquetes_ruta_id");

                    b.ToTable("paquetes", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entities.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino");

                    b.Property<decimal>("Distancia")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.Property<decimal>("TiempoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("tiempo_estimado");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rutas");

                    b.ToTable("rutas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c67f8901-2345-f012-3456-789012345f01"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Destino = "Guadalajara",
                            Distancia = 550.5m,
                            IsActive = true,
                            Origen = "Ciudad de México",
                            TiempoEstimado = 6.5m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a45d6789-0123-def0-1234-567890123def"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Destino = "Nuevo Laredo",
                            Distancia = 220.0m,
                            IsActive = true,
                            Origen = "Monterrey",
                            TiempoEstimado = 2.8m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b56e7890-1234-ef01-2345-678901234ef0"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Destino = "Mérida",
                            Distancia = 300.2m,
                            IsActive = true,
                            Origen = "Cancún",
                            TiempoEstimado = 4.0m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Common.PaqueteHistorial", b =>
                {
                    b.HasOne("CleanArchitecture.PracticalTest.Domain.Entities.Estado", "PaqueteEstado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_paquete_historial_estados_estado_id");

                    b.HasOne("CleanArchitecture.PracticalTest.Domain.Entities.Paquete", "Paquete")
                        .WithMany("Historial")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paquete_historial_paquetes_paquete_id");

                    b.Navigation("Paquete");

                    b.Navigation("PaqueteEstado");
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entities.Paquete", b =>
                {
                    b.HasOne("CleanArchitecture.PracticalTest.Domain.Entities.Estado", "EstadoPaquete")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_estados_estado_id");

                    b.HasOne("CleanArchitecture.PracticalTest.Domain.Entities.Ruta", "RutaSeleccionada")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .HasConstraintName("fk_paquetes_rutas_ruta_id");

                    b.Navigation("EstadoPaquete");

                    b.Navigation("RutaSeleccionada");
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
